version: '2.4'
services:
  prometheus:
    image: "prom/prometheus:v2.16.0"
    container_name: prometheus
    # REPLACE LOCALHOST WITH THE SERVER IP IF YOU WILL ACCESS IT FROM ANOTHER SERVER
    hostname: localhost
    restart: unless-stopped
    mem_limit: 4G
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - "./prometheus/:/etc/prometheus/"
      - "prometheus_data:/prometheus"
    networks:
      - "monitoring"
  node-exporter:
    image: prom/node-exporter:v0.18.1
    container_name: nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
     - "monitoring"
volumes:
  prometheus_data:
networks:
  monitoring: